How to pass
	Env variables
	as a file
		vol

# Generate a Secrets
# Commmand Line
$ echo -n 'root' > ./username.txt
$ echo -n 'password' > ./password.txt
$ kubectl create secret generic db-user-pass --from-file=./username.txt --from-file=./password.txt

$ kubect create secret generic ssl-certificatte --from-file=ssh-privatekey=~/.ssh/id_rsa --ssl-cert-=ssl-cert=mysslcert.crt


# Yaml way
$ echo -n 'root' | base64
$ echo -n 'password' | base64

apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  username: cm9vdA==
  password: cGFzc3dvcmQ=
